spring:
  application:
    name: limiter-client
  cloud:
    sentinel:
      transport:
        port: 8721
        client-ip: 192.168.2.119
        dashboard: localhost:8858
      eager: true

server:
  port: 11111

logging:
  level:
    com:
      alibaba:
        cloud:
          sentinel: debug